/*
 * This source file was generated by the Gradle 'init' task
 */
package arvores;

import arvores.trees.*;

public class App {

    public static void main(String[] args) {
        var tree = new Tree();

        var treeNode = tree.insertRoot(500);

        Pprint.genDecorations(30);

        System.out.println("Raíz da árvore: " + treeNode);
        System.out.println("Valor da raíz: " + treeNode.getItem());

        Pprint.genDecorations(30);

        System.out.println("Raíz: " + tree.getRoot());
        System.out.println("Tamanho da árvore: " + tree.getSize());
    }
}
